name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      release_level:
        description: 'version of release to bump'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

  # pull_request:
  #   branches:
  #     - master
  # push:
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 0 1 * 0

jobs:
  build:
    timeout-minutes: 10
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      # PORT: 50051
      PROJECT: dotnet-template
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'Windows'
        run: rm 'C:\Windows\System32\bash.exe'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: make compile
      - if: runner.os != 'Windows'
        run: curl https://i.jpillora.com/ktr0731/evans@v0.10.9! | bash
      - if: runner.os != 'Windows'
        run: make test_build
        shell: bash
      - run: make build
        shell: bash
      - uses: actions/setup-node@v3
      - if: runner.os != 'Windows'
        run: |
          export PACT_PLUGIN_DIR=$GITHUB_WORKSPACE/../
          cd test/pact-js/plugins
          npm i
          npm run test:consumer
          # npm run test:provider
      - if: runner.os == 'Windows'
        run: |
          export PACT_PLUGIN_DIR=$GITHUB_WORKSPACE\\..\\
          cd test/pact-js/plugins
          npm i
          npm run test:consumer
          # npm run test:provider


# Packaging stuff

      - name: Prepare Artifacts
        run: make x-plat
      - name: Prepare Artifacts
        run: make prepare

      - name: Upload Artifacts - windows-aarch64
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-windows-aarch64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-windows-aarch64.gz
      - name: Upload Artifacts - windows-x86_64
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-windows-x86_64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-windows-x86_64.gz
      - name: Upload Artifacts - linux-x86_64
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-linux-x86_64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-linux-x86_64.gz
      - name: Upload Artifacts - linux-aarch64
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-linux-aarch64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-osx-aarch64.gz
      - name: Upload Artifacts - osx-x86_64
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-osx-x86_64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-osx-x86_64.gz
      - name: Upload Artifacts - osx-aarch64
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: pact-${{ env.PROJECT }}-plugin-osx-aarch64.gz
          path: dist/release/pact-${{ env.PROJECT }}-plugin-osx-aarch64.gz
      - name: Upload Artifacts - Manifest
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: pact-plugin.json
          path: dist/release/pact-plugin.json

# Release stuff 

      - name: set version
        run: |
          echo "PLUGIN_VERSION=$(./script/bump.sh -p 'v-' -l)-$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
          echo "DRAFT=true" >> $GITHUB_ENV
      - name: set release level
        if:  github.ref == 'refs/heads/main' && github.event.inputs.release_level
        run: |
          ./script/bump.sh -p v- ${{ github.event.inputs.release_level }}
          echo "PLUGIN_VERSION=$(./script/bump.sh -p v- -l)" >> $GITHUB_ENV
          echo "DRAFT=false" >> $GITHUB_ENV
      - name: Release Windows
        uses: softprops/action-gh-release@v1
        if: runner.os == 'Windows'
        with:
          files: |
            dist/release/pact-${{ env.PROJECT }}-plugin-windows-x86_64.gz
          prerelease: ${{ env.DRAFT }}
          tag_name: v-${{ env.PLUGIN_VERSION }}
          name: ${{ env.PLUGIN_VERSION }}
          target_commitish: ${{ github.sha }}
      - name: Release Linux
        uses: softprops/action-gh-release@v1
        if: runner.os == 'Linux'
        with:
          files: |
            dist/release/pact-plugin.json
            dist/release/pact-${{ env.PROJECT }}-plugin-linux-x86_64.gz
          prerelease: ${{ env.DRAFT }}
          tag_name: v-${{ env.PLUGIN_VERSION }}
          name: ${{ env.PLUGIN_VERSION }}
          target_commitish: ${{ github.sha }}
      - name: Release macOS
        uses: softprops/action-gh-release@v1
        if: runner.os == 'macOS'
        with:
          files: |
            dist/release/pact-${{ env.PROJECT }}-plugin-osx-x86_64.gz
            dist/release/pact-${{ env.PROJECT }}-plugin-osx-aarch64.gz
          prerelease: ${{ env.DRAFT }}
          tag_name: v-${{ env.PLUGIN_VERSION }}
          name: ${{ env.PLUGIN_VERSION }}
          target_commitish: ${{ github.sha }}