name: Build

on:
  push:
  workflow_dispatch:

jobs:
  dart:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: dart-lang/setup-dart@v1.3
      - run: TARGET=dart make compile
      # - run: curl https://i.jpillora.com/ktr0731/evans@v0.10.9! | bash
      - name: Install evans
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: ktr0731/evans
          tag: v0.10.9
      - run: TARGET=dart make -i test